import type { Product } from "./types";

const now = new Date().toISOString();

export const SAMPLE_PRODUCTS: Product[] = [
  {
    id: "prod-shoe-1",
    name: "Puma Ignite Hybrid Sports Running Shoes",
    description: "Lightweight running shoes with responsive cushioning and breathable mesh upper.",
    price: 4499,
    originalPrice: 5999,
    discount: 25,
    brand: "Puma",
    category: "Shoes",
    rating: 4.6,
    reviewsCount: 812,
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600",
    images: ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600"],
    specifications: { Material: "Mesh", Sole: "Rubber", Closure: "Lace-up" },
    stock: 24,
    isFeatured: true,
    isTrending: true,
    createdAt: now,
  },
  {
    id: "prod-shoe-2",
    name: "Clarks Leather Formal Brogue Shoes",
    description: "Handcrafted genuine leather brogues for a timeless formal look.",
    price: 6999,
    originalPrice: 8999,
    discount: 22,
    brand: "Clarks",
    category: "Shoes",
    rating: 4.4,
    reviewsCount: 340,
    image: "https://images.unsplash.com/photo-1533867617858-e7b97e060509?w=600",
    stock: 3,
    createdAt: now,
  },
  {
    id: "prod-jewel-1",
    name: "Tanishq 22K Gold Pendant Necklace",
    description: "Elegant handcrafted gold pendant with intricate traditional detailing.",
    price: 45999,
    originalPrice: 49999,
    discount: 8,
    brand: "Tanishq",
    category: "Jewellery",
    rating: 4.9,
    reviewsCount: 156,
    image: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=600",
    specifications: { Purity: "22K", Metal: "Gold", Weight: "8.2g" },
    stock: 5,
    isFeatured: true,
    createdAt: now,
  },
  {
    id: "prod-jewel-2",
    name: "CaratLane Silver Diamond Stud Earrings",
    description: "Sparkling diamond stud earrings set in 925 sterling silver.",
    price: 8999,
    brand: "CaratLane",
    category: "Jewellery",
    rating: 4.7,
    reviewsCount: 210,
    image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600",
    stock: 12,
    createdAt: now,
  },
  {
    id: "prod-grocery-1",
    name: "Aashirvaad Whole Wheat Atta 5kg",
    description: "100% whole wheat flour, stone ground for soft rotis.",
    price: 289,
    brand: "Aashirvaad",
    category: "Grocery",
    rating: 4.5,
    reviewsCount: 980,
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600",
    stock: 150,
    createdAt: now,
  },
  {
    id: "prod-grocery-2",
    name: "Tata Sampann Toor Dal 1kg",
    description: "Premium quality unpolished toor dal, rich in protein.",
    price: 189,
    brand: "Tata Sampann",
    category: "Grocery",
    rating: 4.3,
    reviewsCount: 421,
    image: "https://images.unsplash.com/photo-1585996950442-0dbb440683a5?w=600",
    stock: 200,
    createdAt: now,
  },
  {
    id: "prod-beauty-1",
    name: "Minimalist Vitamin C Face Serum",
    description: "10% Vitamin C serum for brighter, even-toned skin.",
    price: 599,
    originalPrice: 799,
    discount: 25,
    brand: "Minimalist",
    category: "Beauty",
    rating: 4.5,
    reviewsCount: 650,
    image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600",
    stock: 80,
    isTrending: true,
    createdAt: now,
  },
  {
    id: "prod-kitchen-1",
    name: "Prestige Svachh Aluminium Pressure Cooker 5L",
    description: "Deep lid pressure cooker with unique gasket-release system for spillage control.",
    price: 1899,
    originalPrice: 2399,
    discount: 20,
    brand: "Prestige",
    category: "Kitchen",
    rating: 4.6,
    reviewsCount: 1230,
    image: "https://images.unsplash.com/photo-1585515320310-259814833e62?w=600",
    stock: 45,
    createdAt: now,
  },
  {
    id: "prod-decor-1",
    name: "Ceramic Textured Flower Vase",
    description: "Hand-finished ceramic vase, perfect centerpiece for living spaces.",
    price: 1299,
    brand: "Home Centre",
    category: "Home Decor",
    rating: 4.4,
    reviewsCount: 88,
    image: "https://images.unsplash.com/photo-1578500494198-246f612d3b3d?w=600",
    stock: 30,
    createdAt: now,
  },
  {
    id: "prod-laptop-1",
    name: "Apple MacBook Air M3 13-inch",
    description: "Ultra-thin laptop with the powerful M3 chip and all-day battery life.",
    price: 114900,
    originalPrice: 119900,
    discount: 4,
    brand: "Apple",
    category: "Laptops",
    rating: 4.9,
    reviewsCount: 2044,
    image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600",
    specifications: { Processor: "Apple M3", RAM: "8GB", Storage: "256GB SSD" },
    stock: 18,
    isFeatured: true,
    isFlashSale: true,
    createdAt: now,
  },
  {
    id: "prod-mobile-1",
    name: "Apple iPhone 16 Pro",
    description: "Titanium design with the A18 Pro chip and pro-grade camera system.",
    price: 134900,
    brand: "Apple",
    category: "Mobiles",
    rating: 4.8,
    reviewsCount: 3021,
    image: "https://images.unsplash.com/photo-1592286927505-1def25115481?w=600",
    stock: 9,
    isTrending: true,
    createdAt: now,
  },
  {
    id: "prod-watch-1",
    name: "Titan Neo Analog Steel Watch",
    description: "Classic stainless steel analog watch with sapphire-coated glass.",
    price: 3495,
    brand: "Titan",
    category: "Watches",
    rating: 4.5,
    reviewsCount: 512,
    image: "https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=600",
    stock: 60,
    createdAt: now,
  },
  {
    id: "prod-fashion-1",
    name: "Fabindia Cotton Kurta - Men",
    description: "Breathable pure cotton kurta with traditional block print.",
    price: 1499,
    brand: "Fabindia",
    category: "Fashion",
    rating: 4.3,
    reviewsCount: 190,
    image: "https://images.unsplash.com/photo-1622470953794-aa9c70b0fb9d?w=600",
    stock: 70,
    createdAt: now,
  },
  {
    id: "prod-furniture-1",
    name: "Urban Ladder Oakland Study Table",
    description: "Solid sheesham wood study table with a spacious drawer.",
    price: 12999,
    brand: "Urban Ladder",
    category: "Furniture",
    rating: 4.6,
    reviewsCount: 145,
    image: "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=600",
    stock: 15,
    createdAt: now,
  },
  {
    id: "prod-gaming-1",
    name: "Sony PlayStation 5 Slim",
    description: "Next-gen gaming console with ultra-high-speed SSD and ray tracing.",
    price: 49990,
    brand: "Sony",
    category: "Gaming",
    rating: 4.9,
    reviewsCount: 987,
    image: "https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=600",
    stock: 6,
    isFlashSale: true,
    createdAt: now,
  },
  {
    id: "prod-electronics-1",
    name: "Sony WH-1000XM5 Wireless Headphones",
    description: "Industry-leading noise cancellation with 30-hour battery life.",
    price: 26990,
    originalPrice: 34990,
    discount: 23,
    brand: "Sony",
    category: "Electronics",
    rating: 4.8,
    reviewsCount: 1560,
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600",
    stock: 22,
    isFeatured: true,
    createdAt: now,
  },
  {
    id: "prod-book-1",
    name: "Atomic Habits - James Clear",
    description: "A proven framework for building good habits and breaking bad ones.",
    price: 399,
    originalPrice: 599,
    discount: 33,
    brand: "Penguin",
    category: "Books",
    rating: 4.8,
    reviewsCount: 5200,
    image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=600",
    stock: 100,
    isTrending: true,
    createdAt: now,
  },
];
